### ISSUE TITLE
Upload event

### ISSUE THREAD

**Issue by h311x** [mengdu/m-quill-editor#2]
Hey!
I've got a question about the 'Upload event'.

So when I was messing with your demo, I noticed that the upload event fires up only when you upload an image by clicking on the 'upload button', but when I drag'n'drop the image on top of the text editor, it does not. And instead of running that function you wrote, it just inserts the dragged image.

So is this a bug? Or there are ways to prevent that from happening?

**Comment by mengdu** [comment]
Oh, this component does not support drag and drop pictures. You may be drag picture of other website.

**Comment by h311x** [comment]
Thanks for answering!

Could you tell me one more thing please?
If the component does not support drag and drop, how can i disable this feature entirely so my users won't do it by accident? :)

**Comment by mengdu** [comment]
This drag-and-drop function for inserting pictures is the default behavior of the editor. I don't know how to disable it. You can look up on [quill](https://quilljs.com/docs/quickstart/) documents for help.

**Comment by h311x** [comment]
Gotcha! I appreciate that you take the time to answer my questions!

This will be the last one :)

I noticed that you are using some kind of a custom module to enable the "fullscreen mode". Could you please tell me how could I get rid of that behavior?

**Comment by mengdu** [comment]
Can you describe the problem in detail? I don't quite understand your question.

**Comment by h311x** [comment]
Ok, so if you'll open your example on https://mengdu.github.io/m-quill-editor/example/ , you can see in the top right corner a button that turns the "fullscreen mode" on. Basically the question is - how do I remove the toolbar button that is responsible for turning the fullscreen mode on and off as well as disable this mode entirely :)

**Comment by h311x** [comment]
Omg, just found the attribute for that. Sorry and thanks again :+1:
